language: node_js
node_js:
  - "8.11.1"
script:
  - npm run build
  - npm run watch-css
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN